import 'dart:convert';
import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:apidash/models/models.dart';
import 'package:apidash/services/hive_services.dart';

class McpSyncService {
  static const String _syncFileName = 'apidash_mcp_workspace.json';

  /// Gets the path to the shared synchronization file
  static Future<File> getSyncFile() async {
    final directory = await getApplicationSupportDirectory();
    return File('${directory.path}/$_syncFileName');
  }

  /// Exports current collections and environments to the JSON sync file
  /// for the MCP Node.js server to read natively.
  static Future<void> syncWorkspaceToMcp(
    List<RequestModel>? requests,
    List<dynamic>? environments,
  ) async {
    try {
      final syncFile = await getSyncFile();
      
      final Map<String, dynamic> workspaceData = {
        'lastUpdated': DateTime.now().toIso8601String(),
        'requests': requests?.map((r) => r.toJson()).toList() ?? [],
        'environments': environments?.toList() ?? [],
      };

      await syncFile.writeAsString(jsonEncode(workspaceData));
    } catch (e) {
      // Gracefully handle file write errors so the main app doesn't crash
      print('Failed to sync APIDash workspace for MCP: $e');
    }
  }

  /// Helper to trigger a full sync directly from the local Hive Box
  static Future<void> forceSyncFromHive() async {
    final hiveService = HiveHandler();
    // Assuming HiveHandler can retrieve requests/environments
    // For this bridge, we construct the request array manually if needed
    // or rely on state management (Riverpod) to call syncWorkspaceToMcp.
    
    // In actual implementation, connect this to your Riverpod ProviderListener
    // whenever the collection or environments list updates.
  }

  /// Watches the sync file for updates generated by the MCP Server (e.g., modified env vars)
  static Future<void> watchMcpWorkspace() async {
    final syncFile = await getSyncFile();
    // Assuming watcher package is added: import 'package:watcher/watcher.dart';
    // final watcher = FileWatcher(syncFile.path);
    // watcher.events.listen((event) {
    //   if (event.type == ChangeType.MODIFY) {
    //     // Trigger Riverpod to reload state from the JSON
    //   }
    // });
    print('Started watching \${syncFile.path} for MCP updates...');
  }
}
